### ISSUE TITLE
Connection issue between Docker containers using Qdrant client

### ISSUE THREAD

**Issue by amirhosein-vedadi** [AstraBert/qdurllm#1]
## Description
I'm experiencing a connection issue between my application container and the Qdrant service container in a Docker Compose setup. The application is unable to connect to the Qdrant service, resulting in a "Name or service not known" error.

## Error Msg
Traceback (most recent call last):
  ...
httpcore.ConnectError: [Errno -2] Name or service not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  ...
qdrant_client.http.exceptions.ResponseHandlingException: [Errno -2] Name or service not known

## Steps to Reproduce
1. Run docker-compose up.
2. The local-search-application container fails to connect to the Qdrant service.

### Expected Behavior
The local-search-application should be able to connect to the Qdrant service using the service name as the hostname within the Docker network.
### Actual Behavior
The application fails to resolve the hostname "qdrant" and cannot connect to the Qdrant service.

**Comment by AstraBert** [comment]
Hi @amirhosein-vedadi,

This might happen sometimes: would you mind telling me on what OS and with what version of docker and docker-compose are you running the application?

**Comment by amirhosein-vedadi** [comment]
Hi @AstraBert,

- Docker version: 27.0.3
- Docker Compose version: v2.28.1
- Python version: 3.10
- Operating System: Ubuntu 22.04

**Comment by AstraBert** [comment]
Ok thanks!

Docker and docker-compose seem ok, I'll test the application on my Ubuntu to see wether there is any problem and, if so, how we can fix it :)

Thanks for bringing that up!

**Comment by AstraBert** [comment]
Hi @amirhosein-vedadi,

I'm closing the issue for now due to inactivity and no other reported cases: feel free to reopen it if needed.

Cheers,
Astra :)
